[tool.poetry]
name = "cv-render"
version = "0.1.0"
description = ""
authors = ["Pablo D <pabloddlh@ext.inditex.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rendercv = "^1.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
